### ISSUE TITLE
Cool App

### ISSUE THREAD

**Issue by frankyxcs** [TheJuanAndOnly/MySchoolAppv1.3#1]
Hi very cool app ! 

if you have time i have 3 suggestions !! 

- grades 1 - 10 ( i´m living in spain )
- A timetabel from monday to saturday and adding hours with the school subject would be cool 
(e.g.   Monday  08.00  Math, 09.00 Bilologie, 10.00 
          Tuesday 08.00   Nature ......
and so on ...

- Adding normal Text notes with description 

if you have some time to make it possible 

but very very nice work from you ..perfect for my school

thanx Frank

**Comment by Dunoo** [comment]
Hey frankyxcs!

We are not sure if you got our email as a respond to these suggestions but here is how things are at the moment.

 Yesterday we released this app on google play under the name: "GradeDay" (link: https://play.google.com/store/apps/details?id=com.thejuanandonly.schoolapp ). We added the 10-grade-system, as you might already know, unfortunately without predictions, which will be implemented soon. As for the timetable and text notes, we are working on it and might be available in the upcoming update (very, very soon).

Your GradeDay team

**Comment by frankyxcs** [comment]
Hi 

yes very nice work but i know it is difficult to get this correct working, because the grade system is very different in a lot of countries . For example spain  1- 10 (means 10 is the best and 1 is the worst grade its not the same like in germany). Germany 1 - 6 (primary school thats OK (1 is best 6 is the worst)

Or germany (i think high school) has a point system 1 - 15 (15 is the best and 0 the worst). 

You made a very nice work and i think it is hard to consider all these values. 

frank

**Comment by Dunoo** [comment]
Yes, it is pretty hard, that's why we are taking so long to get it working. Other than that, is everything working correct? (If you have tried it) ^^

**Comment by frankyxcs** [comment]
yes only the picture notes ...it working fine so far but in my opinion the com.davemorrissey.labs:subsampling-scale-image-view:3.4.1 
is not the best. If you add for example more than 10 pictures (for example galaxy s3 mini) it is getting very slow and running out of memory 

also the avatar ... you are getting the image with this 
android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI

so it is possibile to get an image from google drive too but only with one time  permission. Next time you start the app and a link from google drive is saved the app crashes, because the link is not available anymore.

another  bug is (its not a bug but throws invalid double) because in some countries you have "," instead of "." 
i have solved this by adding us format to every decimal format so every time a dot will be  used . 

 DecimalFormat df = new DecimalFormat("#",new DecimalFormatSymbols(Locale.US));

also if you go to target 23 you should consider adding permissions request read/write. i have added this to loginactivity so android 6.0 can request the permissions

 String[] PERMISSIONS = { Manifest.permission.WRITE_EXTERNAL_STORAGE,Manifest.permission.READ_EXTERNAL_STORAGE};

        if(!hasPermissions(this, PERMISSIONS)){
            ActivityCompat.requestPermissions(this, PERMISSIONS, PERMISSION_WRITE_STORAGE);
        }

and on the end 

public static boolean hasPermissions(Context context, String... permissions) {
        if ((android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) && context != null && permissions != null) {
            for (String permission : permissions) {
                if (ActivityCompat.checkSelfPermission(context, permission) != PackageManager.PERMISSION_GRANTED) {
                    return false;
                }
            }
        }
        return true;
    }


greets frank

**Comment by SurlierBacchus** [comment]
Thank you for the feedback Frank!

The way i have dealt with permissions on Android 6 is that I only require the user to accept them if it's necessary. So when you open the navigation drawer or go to image notes you can accept it to use these features or decline and everything else still works fine. 

As for the decimal numbers, one of our beta testers has reported this issue but we had no clue what caused it so thanks for the tip!

I personally have not developed any of the image features so I will delegate this to my colleague and we will see how well we can solve the memory issues without it being too time consuming. 

Once again thank you for all your tips and feel free to write back if you know about any other issues!

Róbert Gers,
GradeDay developing team

**Comment by SurlierBacchus** [comment]
We are closing this repository down now so if you have anything else to say, please refer to our e-mail - gradeday.team@gmail.com
